services:
  # SlackBot Web Service
  - type: web
    name: slack-ai-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python slack_vector_bot.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
      - key: SLACK_BOT_TOKEN
        sync: false
      - key: SLACK_APP_TOKEN
        sync: false
      - key: PORT
        value: 3000

  # 定期実行（Slackメッセージ取得・ベクトル化）
  - type: worker
    name: slack-message-processor
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python slack_to_supabase.py
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: OPENAI_API_KEY
        sync: false
    plan: free

crons:
  # 毎日午前9時にSlackメッセージを処理
  - name: daily-slack-processing
    service: slack-message-processor
    schedule: "0 9 * * *"
    command: python slack_to_supabase.py 